// frontend/src/components/layout/Header.tsx
'use client';

import { useState, useRef, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { usePathname, useRouter } from 'next/navigation';
import { useAuth } from '@/lib/auth-context';
import ConfirmationModal from '@/components/shared/ConfirmationModal';

export default function Header() {
  const { user, isAuthenticated, logout } = useAuth();
  const pathname = usePathname();
  const router = useRouter();

  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [showLogoutModal, setShowLogoutModal] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsDropdownOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  useEffect(() => {
    setIsMobileMenuOpen(false);
    setIsDropdownOpen(false);
  }, [pathname]);

  const isActive = (path: string) => pathname === path;

  const getInitials = () => {
    if (!user?.username) return '?';
    return user.username.charAt(0).toUpperCase();
  };

  const handleLogoutClick = () => {
    setIsDropdownOpen(false);
    setIsMobileMenuOpen(false);
    setShowLogoutModal(true);
  };

  const confirmLogout = () => {
    setShowLogoutModal(false);
    logout();
  };

  return (
    <>
      <header className="w-full bg-orange-100 shadow-md">
        <div className="container-responsive">
          <div className="flex items-center justify-between h-14 sm:h-16">
            {/* Logo */}
            <Link href="/" className="text-xl sm:text-2xl md:text-3xl font-bold text-orange-600 cursor-pointer transition-colors hover:text-orange-700">
              Lost & Found
            </Link>

            {/* Desktop Navigation */}
            <nav className="hidden md:flex items-center gap-6 lg:gap-8">
              <Link
                href="/home"
                className={`hover:text-orange-500 transition-colors duration-200 text-sm lg:text-base ${
                  isActive('/home') ? 'text-orange-600 font-semibold' : 'text-gray-700'
                }`}
              >
                Home
              </Link>
              {isAuthenticated && (
                <>
                  <Link
                    href="/dashboard"
                    className={`hover:text-orange-500 transition-colors duration-200 text-sm lg:text-base ${
                      isActive('/dashboard') ? 'text-orange-600 font-semibold' : 'text-gray-700'
                    }`}
                  >
                    Dashboard
                  </Link>
                  <Link
                    href="/items"
                    className={`hover:text-orange-500 transition-colors duration-200 text-sm lg:text-base ${
                      isActive('/items') ? 'text-orange-600 font-semibold' : 'text-gray-700'
                    }`}
                  >
                    Public Posts
                  </Link>
                </>
              )}
            </nav>

            {/* Right side */}
            <div className="flex items-center gap-3">
              {isAuthenticated ? (
                /* User Menu */
                <div className="relative" ref={dropdownRef}>
                  <button
                    onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                    className="flex items-center gap-2"
                  >
                    <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-full overflow-hidden border-2 border-orange-300 flex items-center justify-center bg-orange-200">
                      {user?.avatar ? (
                        <Image
                          src={user.avatar}
                          alt={user.username}
                          width={32}
                          height={32}
                          className="w-8 h-8 rounded-full object-cover"
                        />
                      ) : (
                        <span className="text-orange-700 font-semibold text-sm sm:text-base">
                          {getInitials()}
                        </span>
                      )}
                    </div>
                  </button>

                  {isDropdownOpen && (
                    <div className="dropdown-responsive animate-scale-in">
                      <div className="px-4 py-3 border-b border-gray-100">
                        <p className="text-sm font-medium text-gray-900 truncate">
                          {user?.username}
                        </p>
                        <p className="text-xs text-gray-500 truncate">{user?.email}</p>
                      </div>
                      <Link
                        href="/profile"
                        className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-orange-50 transition-colors"
                        onClick={() => setIsDropdownOpen(false)}
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                        </svg>
                        Profile
                      </Link>
                      <Link
                        href="/help-support"
                        className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-orange-50 transition-colors"
                        onClick={() => setIsDropdownOpen(false)}
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                        Help & Support
                      </Link>
                      <div className="border-t border-gray-100 mt-1 pt-1">
                        <button
                          onClick={handleLogoutClick}
                          className="flex items-center gap-3 w-full px-4 py-2.5 text-sm text-red-600 hover:bg-red-50 transition-colors"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                          </svg>
                          Logout
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                /* Guest Buttons */
                <div className="hidden md:flex items-center gap-2">
                  <Link
                    href="/auth/sign-in"
                    className="btn-responsive-sm bg-orange-600 text-white hover:bg-orange-700 rounded-md"
                  >
                    Sign In
                  </Link>
                  <Link
                    href="/auth/sign-up"
                    className="btn-responsive-sm border border-orange-600 text-orange-600 hover:bg-orange-50 rounded-md"
                  >
                    Sign Up
                  </Link>
                </div>
              )}

              {/* Mobile Menu Button */}
              <button
                onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                className="md:hidden p-2 rounded-md text-gray-700 hover:bg-orange-200 transition-colors"
              >
                {isMobileMenuOpen ? (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                ) : (
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Mobile Menu */}
        {isMobileMenuOpen && (
          <div className="md:hidden bg-white border-t border-orange-200 shadow-lg animate-slide-down">
            <nav className="container-responsive py-4 space-y-2">
              <Link
                href="/home"
                className={`block px-4 py-2 rounded-md text-sm transition-colors ${
                  isActive('/home')
                    ? 'bg-orange-100 text-orange-600 font-semibold'
                    : 'text-gray-700 hover:bg-orange-50'
                }`}
              >
                Home
              </Link>
              {isAuthenticated ? (
                <>
                  <Link
                    href="/dashboard"
                    className={`block px-4 py-2 rounded-md text-sm transition-colors ${
                      isActive('/dashboard')
                        ? 'bg-orange-100 text-orange-600 font-semibold'
                        : 'text-gray-700 hover:bg-orange-50'
                    }`}
                  >
                    Dashboard
                  </Link>
                  <Link
                    href="/items"
                    className={`block px-4 py-2 rounded-md text-sm transition-colors ${
                      isActive('/items')
                        ? 'bg-orange-100 text-orange-600 font-semibold'
                        : 'text-gray-700 hover:bg-orange-50'
                    }`}
                  >
                    Public Posts
                  </Link>
                  <div className="border-t border-gray-200 pt-2 mt-2">
                    <button
                      onClick={handleLogoutClick}
                      className="flex items-center gap-2 w-full px-4 py-2 text-sm text-red-600 hover:bg-red-50 rounded-md transition-colors"
                    >
                      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                      </svg>
                      Logout
                    </button>
                  </div>
                </>
              ) : (
                <div className="border-t border-gray-200 pt-3 mt-2 flex flex-col gap-2 px-4">
                  <Link
                    href="/auth/sign-in"
                    className="btn-responsive-sm bg-orange-600 text-white hover:bg-orange-700 rounded-md text-center"
                  >
                    Sign In
                  </Link>
                  <Link
                    href="/auth/sign-up"
                    className="btn-responsive-sm border border-orange-600 text-orange-600 hover:bg-orange-50 rounded-md text-center"
                  >
                    Sign Up
                  </Link>
                </div>
              )}
            </nav>
          </div>
        )}
      </header>

      <ConfirmationModal
        isOpen={showLogoutModal}
        title="Confirm Logout"
        message="Are you sure you want to log out? You will need to sign in again to access your account."
        confirmLabel="Logout"
        variant="danger"
        onConfirm={confirmLogout}
        onCancel={() => setShowLogoutModal(false)}
      />
    </>
  );
}

// frontend/src/app/layout/header/header.component.ts
import { Component, inject, signal, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AsyncPipe } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule, AsyncPipe],
  template: `
    <header class="w-full bg-orange-100 shadow-md">
      <div class="container-responsive">
        <div class="flex-responsive-between py-3 sm:py-4">
          <!-- Logo -->
          <div class="text-xl sm:text-2xl md:text-3xl font-bold text-orange-600 cursor-pointer transition-colors hover:text-orange-700" 
               (click)="navigateHome()">
            Lost & Found
          </div>
          
          <!-- Desktop Navigation Links -->
          <nav class="hidden md:flex items-center space-x-4 lg:space-x-6 text-gray-800 font-medium">
            <a routerLink="/home" routerLinkActive="text-orange-600" 
               class="hover:text-orange-500 transition-colors duration-200 text-sm lg:text-base">Home</a>
            <ng-container *ngIf="user$ | async">
              <a routerLink="/dashboard" routerLinkActive="text-orange-600" 
                 class="hover:text-orange-500 transition-colors duration-200 text-sm lg:text-base">Dashboard</a>
              <a routerLink="/items" routerLinkActive="text-orange-600" 
                 class="hover:text-orange-500 transition-colors duration-200 text-sm lg:text-base">All Posts</a>
            </ng-container>
          </nav>
          
          <!-- Auth Buttons & User Menu -->
          <div class="flex items-center space-x-2 sm:space-x-3">
            <ng-container *ngIf="(user$ | async) as user; else guestTemplate">
              <!-- Desktop User Menu -->
              <div class="hidden md:block relative">
                <button 
                  (click)="toggleDropdown()"
                  class="flex items-center gap-2 p-2 rounded-full hover:bg-orange-200 transition-colors duration-200"
                >
                  <!-- User Avatar -->
                  <div class="w-8 h-8 sm:w-10 sm:h-10 rounded-full overflow-hidden border-2 border-orange-300">
                    <img 
                      *ngIf="user.avatar; else avatarFallback"
                      [src]="user.avatar" 
                      [alt]="user.username || user.name || 'User'"
                      class="w-full h-full object-cover"
                    />
                    <ng-template #avatarFallback>
                      <svg class="w-full h-full bg-orange-200 text-orange-600" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/>
                      </svg>
                    </ng-template>
                  </div>
                  <!-- Dropdown Arrow -->
                  <svg 
                    class="w-3 h-3 sm:w-4 sm:h-4 text-gray-600 transition-transform duration-200"
                    [class.rotate-180]="isDropdownOpen()"
                    fill="none" 
                    stroke="currentColor" 
                    viewBox="0 0 24 24"
                  >
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
                  </svg>
                </button>

                <!-- Desktop Dropdown Menu -->
                <div 
                  *ngIf="isDropdownOpen()"
                  class="dropdown-responsive"
                >
                  <!-- User Info -->
                  <div class="px-4 py-3 border-b border-gray-100">
                    <p class="text-sm font-medium text-gray-900 truncate">{{ user.username || user.name || 'User' }}</p>
                    <p class="text-xs text-gray-500 truncate">{{ user.email }}</p>
                  </div>
                  
                  <!-- Menu Items -->
                  <a 
                    routerLink="/profile" 
                    (click)="closeDropdown()"
                    class="flex items-center gap-3 px-4 py-3 text-sm text-gray-700 hover:bg-orange-50 transition-colors"
                  >
                    <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                    <span>Profile</span>
                  </a>
                  
                  <a 
                    routerLink="/help-support" 
                    (click)="closeDropdown()"
                    class="flex items-center gap-3 px-4 py-3 text-sm text-gray-700 hover:bg-orange-50 transition-colors"
                  >
                    <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span>Help & Support</span>
                  </a>
                  
                  <button 
                    (click)="showLogoutConfirmation()"
                    class="w-full flex items-center gap-3 px-4 py-3 text-sm text-red-600 hover:bg-red-50 transition-colors"
                  >
                    <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
                    </svg>
                    <span>Logout</span>
                  </button>
                </div>
              </div>
              
              <!-- Mobile User Avatar -->
              <div class="md:hidden">
                <button 
                  (click)="toggleMobileMenu()"
                  class="flex items-center gap-2 p-2 rounded-full hover:bg-orange-200 transition-colors duration-200"
                >
                  <div class="w-8 h-8 rounded-full overflow-hidden border-2 border-orange-300">
                    <img 
                      *ngIf="user.avatar; else mobileAvatarFallback"
                      [src]="user.avatar" 
                      [alt]="user.username || user.name || 'User'"
                      class="w-full h-full object-cover"
                    />
                    <ng-template #mobileAvatarFallback>
                      <svg class="w-full h-full bg-orange-200 text-orange-600" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/>
                      </svg>
                    </ng-template>
                  </div>
                  <svg 
                    class="w-4 h-4 text-gray-600 transition-transform duration-200"
                    [class.rotate-180]="isMobileMenuOpen()"
                    fill="none" 
                    stroke="currentColor" 
                    viewBox="0 0 24 24"
                  >
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
            </ng-container>
            
            <ng-template #guestTemplate>
              <!-- Guest User Buttons -->
              <div class="flex items-center space-x-2 sm:space-x-3">
                <a 
                  routerLink="/auth/sign-in" 
                  routerLinkActive="bg-orange-700"
                  class="btn-responsive-sm bg-orange-600 text-white hover:bg-orange-700 transition-colors"
                >
                  <span class="hidden sm:inline">Sign In</span>
                  <span class="sm:hidden">Login</span>
                </a>
                <a 
                  routerLink="/auth/sign-up" 
                  routerLinkActive="bg-orange-50 border-orange-700"
                  class="btn-responsive-sm border border-orange-600 text-orange-600 hover:bg-orange-50 transition-colors"
                >
                  <span class="hidden sm:inline">Sign Up</span>
                  <span class="sm:hidden">Join</span>
                </a>
              </div>
            </ng-template>
          </div>
        </div>
      </div>

      <!-- Mobile Navigation Menu -->
      <div 
        *ngIf="isMobileMenuOpen()"
        class="md:hidden bg-white border-t border-orange-200 shadow-lg animate-slide-down"
      >
        <div class="container-responsive py-4">
          <nav class="space-y-3">
            <a 
              routerLink="/home" 
              routerLinkActive="bg-orange-50 text-orange-600"
              (click)="closeMobileMenu()"
              class="block px-4 py-3 text-gray-800 hover:bg-orange-50 hover:text-orange-600 rounded-lg transition-colors duration-200"
            >
              Home
            </a>
            <ng-container *ngIf="user$ | async">
              <a 
                routerLink="/dashboard" 
                routerLinkActive="bg-orange-50 text-orange-600"
                (click)="closeMobileMenu()"
                class="block px-4 py-3 text-gray-800 hover:bg-orange-50 hover:text-orange-600 rounded-lg transition-colors duration-200"
              >
                Dashboard
              </a>
              <a 
                routerLink="/items" 
                routerLinkActive="bg-orange-50 text-orange-600"
                (click)="closeMobileMenu()"
                class="block px-4 py-3 text-gray-800 hover:bg-orange-50 hover:text-orange-600 rounded-lg transition-colors duration-200"
              >
                All Posts
              </a>
              <a 
                routerLink="/profile" 
                (click)="closeMobileMenu()"
                class="block px-4 py-3 text-gray-800 hover:bg-orange-50 hover:text-orange-600 rounded-lg transition-colors duration-200"
              >
                Profile
              </a>
              <a 
                routerLink="/help-support" 
                (click)="closeMobileMenu()"
                class="block px-4 py-3 text-gray-800 hover:bg-orange-50 hover:text-orange-600 rounded-lg transition-colors duration-200"
              >
                Help & Support
              </a>
              <button 
                (click)="showLogoutConfirmation(); closeMobileMenu()"
                class="w-full text-left px-4 py-3 text-red-600 hover:bg-red-50 rounded-lg transition-colors duration-200"
              >
                Logout
              </button>
            </ng-container>
          </nav>
        </div>
      </div>
    </header>

    <!-- Logout Confirmation Modal -->
    <div 
      *ngIf="showLogoutModal()"
      class="modal-responsive"
      (click)="cancelLogout()"
    >
      <div class="flex items-center justify-center min-h-screen p-4">
        <div 
          class="modal-content-responsive animate-scale-in"
          (click)="$event.stopPropagation()"
        >
          <div class="flex items-center gap-3 mb-4">
            <div class="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 bg-red-100 rounded-full flex items-center justify-center">
              <svg class="w-4 h-4 sm:w-6 sm:h-6 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.888-.833-2.658 0L3.156 16.5c-.77.833.192 2.5 1.732 2.5z" />
              </svg>
            </div>
            <div>
              <h3 class="text-base sm:text-lg font-semibold text-gray-900">Confirm Logout</h3>
              <p class="text-sm text-gray-600 mt-1">Are you sure you want to log out of your account?</p>
            </div>
          </div>
          
          <div class="flex flex-col sm:flex-row gap-3 justify-end">
            <button 
              (click)="cancelLogout()"
              class="btn-responsive-sm text-gray-700 bg-gray-100 hover:bg-gray-200 transition-colors"
            >
              Cancel
            </button>
            <button 
              (click)="confirmLogout()"
              class="btn-responsive-sm text-white bg-red-600 hover:bg-red-700 transition-colors"
            >
              Logout
            </button>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class HeaderComponent {
  private authService = inject(AuthService);
  user$: Observable<any | null> = this.authService.user$;
  
  isDropdownOpen = signal(false);
  isMobileMenuOpen = signal(false);
  showLogoutModal = signal(false);

  // Close dropdown when clicking outside
  @HostListener('document:click', ['$event'])
  onDocumentClick(event: Event) {
    const target = event.target as HTMLElement;
    const dropdown = target.closest('.relative');
    if (!dropdown && this.isDropdownOpen()) {
      this.closeDropdown();
    }
  }

  toggleDropdown(): void {
    this.isDropdownOpen.set(!this.isDropdownOpen());
  }

  closeDropdown(): void {
    this.isDropdownOpen.set(false);
  }

  toggleMobileMenu(): void {
    this.isMobileMenuOpen.set(!this.isMobileMenuOpen());
  }

  closeMobileMenu(): void {
    this.isMobileMenuOpen.set(false);
  }

  showLogoutConfirmation(): void {
    this.closeDropdown();
    this.closeMobileMenu();
    this.showLogoutModal.set(true);
  }

  cancelLogout(): void {
    this.showLogoutModal.set(false);
  }

  confirmLogout(): void {
    this.showLogoutModal.set(false);
    this.authService.logout();
  }

  navigateHome(): void {
    window.location.href = '/';
  }
}
