// frontend/src/components/profile/ProfileHeader.tsx
'use client';

import React from 'react';
import { Calendar, MapPin, Mail } from 'lucide-react';
import { formatLocalDate } from '@/utils/date-formatter';

interface EditForm {
  username: string;
  phone: string;
  location: string;
  bio: string;
  avatar: string;
}

interface ProfileHeaderProps {
  username: string;
  joinDate: string;
  location: string;
  email: string;
  isEditing: boolean;
  editForm: EditForm;
  onEditChange: (field: keyof EditForm, value: string) => void;
}

export default function ProfileHeader({
  username,
  joinDate,
  location,
  email,
  isEditing,
  editForm,
  onEditChange,
}: ProfileHeaderProps) {
  return (
    <div className="text-center mt-5 w-full max-w-sm">
      {/* Username */}
      {isEditing ? (
        <input
          type="text"
          value={editForm.username}
          onChange={(e) => onEditChange('username', e.target.value)}
          className="text-2xl md:text-3xl font-bold text-gray-900 bg-orange-50 border-2 border-orange-200 rounded-xl px-4 py-2 w-full text-center focus:outline-none focus:ring-4 focus:ring-orange-500/10 focus:border-orange-500 transition-all"
          placeholder="Your name"
        />
      ) : (
        <h1 className="text-2xl md:text-3xl font-bold text-gray-900">{username || 'User'}</h1>
      )}

      {/* Email badge */}
      <div className="flex items-center justify-center gap-1.5 mt-2 text-gray-500">
        <Mail className="w-3.5 h-3.5" />
        <span className="text-sm">{email}</span>
      </div>

      {/* Meta info row */}
      <div className="flex flex-wrap items-center justify-center gap-4 mt-4">
        {/* Join date */}
        <div className="flex items-center gap-1.5 text-gray-500">
          <Calendar className="w-4 h-4 text-orange-400" />
          <span className="text-sm">Joined {formatLocalDate(joinDate)}</span>
        </div>

        {/* Location */}
        {isEditing ? (
          <div className="flex items-center gap-1.5">
            <MapPin className="w-4 h-4 text-orange-400" />
            <input
              type="text"
              value={editForm.location}
              onChange={(e) => onEditChange('location', e.target.value)}
              className="text-sm bg-orange-50 border border-orange-200 rounded-lg px-3 py-1.5 text-gray-700 focus:outline-none focus:ring-2 focus:ring-orange-500/20 focus:border-orange-400 transition-all w-36"
              placeholder="Your location"
            />
          </div>
        ) : (
          location && (
            <div className="flex items-center gap-1.5 text-gray-500">
              <MapPin className="w-4 h-4 text-orange-400" />
              <span className="text-sm">{location}</span>
            </div>
          )
        )}
      </div>
    </div>
  );
}

// frontend/src/app/features/profile/components/profile-header/profile-header.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { UserProfile } from '../../models/user-profile.model';
import { formatDate } from '../../utils/date-formatter.util';

@Component({
  selector: 'app-profile-header',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="relative overflow-hidden rounded-3xl bg-gradient-to-br from-orange-500 via-orange-600 to-red-500 shadow-2xl shadow-orange-500/25 transition-all duration-500"
         [class.transform]="isEditing"
         [class.scale-[1.02]]="isEditing">
      <!-- Avatar and User Info Content -->
      <div class="relative p-8 md:p-12">
        <div class="flex flex-col lg:flex-row items-center gap-8 lg:gap-12">
          <!-- Avatar Section -->
          <div class="relative group">
            <!-- Avatar display and upload UI -->
            <ng-content select="[avatarSection]"></ng-content>
          </div>

          <!-- User Info -->
          <div class="flex-1 text-center lg:text-left text-white">
            <div class="mb-4">
              <h1 *ngIf="!isEditing" class="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight mb-2 bg-gradient-to-r from-white to-orange-100 bg-clip-text text-transparent">
                {{ profile.username }}
              </h1>
              <input *ngIf="isEditing"
                     [(ngModel)]="editForm.username"
                     class="text-4xl md:text-5xl font-bold bg-white/10 backdrop-blur-sm border-2 border-white/20 rounded-2xl px-6 py-3 text-white placeholder-white/60 focus:border-white/40 focus:outline-none transition-all duration-300 w-full max-w-lg"
                     placeholder="Enter your username" />
            </div>

            <!-- Meta Info -->
            <div class="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-6 mb-8 text-white/90">
              <!-- Join Date -->
              <div class="flex items-center gap-2">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3a4 4 0 118 0v4m-4 8a4 4 0 11-8 0V11a4 4 0 118 0v4"></path>
                </svg>
                <span class="font-medium">Joined {{ formatDate(profile.joinDate) }}</span>
              </div>

              <!-- Location -->
              <div class="flex items-center gap-2">
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path>
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path>
                </svg>
                <span *ngIf="!isEditing" class="font-medium">{{ profile.location || 'Location not set' }}</span>
                <input *ngIf="isEditing"
                       [(ngModel)]="editForm.location"
                       class="bg-white/10 backdrop-blur-sm border border-white/20 rounded-lg px-3 py-1 text-white placeholder-white/60 focus:border-white/40 focus:outline-none transition-all duration-300"
                       placeholder="Enter location" />
              </div>
            </div>

            <!-- Action Buttons -->
            <div class="flex flex-wrap items-center justify-center lg:justify-start gap-3">
              <ng-content select="[actionButtons]"></ng-content>
            </div>
          </div>
        </div>
      </div>
    </div>
  `
})
export class ProfileHeaderComponent {
  @Input() profile!: UserProfile;
  @Input() isEditing = false;
  @Input() editForm: Partial<UserProfile> = {};
  
  protected formatDate = formatDate;
}
