// frontend/src/app/features/report/components/image-upload/image-upload.component.ts
import { Component, EventEmitter, Input, Output, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CloudinaryService } from '../../../../core/services/cloudinary.service';
import { ToastrService } from 'ngx-toastr';
import { ImageFile } from '../../models/item.model';


@Component({
  selector: 'app-image-upload',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="border-2 border-dashed border-orange-200 rounded-lg p-6 text-center hover:border-orange-300 transition-colors">
      <!-- Upload Area -->
      <div *ngIf="!selectedImage && !uploadedImageUrl" class="space-y-3">
        <ng-container *ngTemplateOutlet="uploadTemplate"></ng-container>
      </div>

      <!-- Selected Image Preview -->
      <div *ngIf="selectedImage && !isUploading && !uploadedImageUrl" class="space-y-3">
        <ng-container *ngTemplateOutlet="previewTemplate"></ng-container>
      </div>

      <!-- Uploading State -->
      <div *ngIf="isUploading" class="space-y-3">
        <ng-container *ngTemplateOutlet="loadingTemplate"></ng-container>
      </div>

      <!-- Uploaded Image -->
      <div *ngIf="uploadedImageUrl" class="space-y-3">
        <ng-container *ngTemplateOutlet="successTemplate"></ng-container>
      </div>
    </div>

    <!-- Upload Template -->
    <ng-template #uploadTemplate>
      <svg class="mx-auto h-12 w-12 text-orange-400" stroke="currentColor" fill="none" viewBox="0 0 48 48">
        <path 
          d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" 
          stroke-width="2" 
          stroke-linecap="round" 
          stroke-linejoin="round"
        />
      </svg>
      <div>
        <input
          type="file"
          accept="image/*"
          class="hidden"
          (change)="onFileSelected($event)"
          #fileInput
        />
        <button
          type="button"
          (click)="fileInput.click()"
          class="bg-orange-600 hover:bg-orange-700 text-white px-4 py-2 rounded-lg transition-colors"
        >
          Choose Image
        </button>
        <p class="text-sm text-orange-600 mt-2">
          PNG, JPG, GIF up to 5MB
        </p>
      </div>
    </ng-template>

    <!-- Preview Template -->
    <ng-template #previewTemplate>
      <img 
        [src]="selectedImage?.preview" 
        alt="Preview" 
        class="mx-auto h-32 w-32 object-cover rounded-lg"
      >
      <p class="text-sm text-orange-700">{{ selectedImage?.file?.name }}</p>
      <p class="text-xs text-orange-600">{{ getFileSize(selectedImage?.file?.size || 0) }}</p>
      <div class="flex justify-center space-x-2">
        <button
          type="button"
          (click)="imageRemoved.emit()"
          class="bg-red-600 hover:bg-red-700 text-white px-3 py-1 text-sm rounded transition-colors"
        >
          Remove
        </button>
        <button
          type="button"
          (click)="fileInput.click()"
          class="bg-orange-600 hover:bg-orange-700 text-white px-3 py-1 text-sm rounded transition-colors"
        >
          Change
        </button>
        <input
          type="file"
          accept="image/*"
          class="hidden"
          (change)="onFileSelected($event)"
          #fileInput
        />
      </div>
    </ng-template>

    <!-- Loading Template -->
    <ng-template #loadingTemplate>
      <svg 
        class="animate-spin mx-auto h-8 w-8 text-orange-600" 
        xmlns="http://www.w3.org/2000/svg" 
        fill="none" 
        viewBox="0 0 24 24"
      >
        <circle 
          class="opacity-25" 
          cx="12" 
          cy="12" 
          r="10" 
          stroke="currentColor" 
          stroke-width="4"
        ></circle>
        <path 
          class="opacity-75" 
          fill="currentColor" 
          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
        ></path>
      </svg>
      <p class="text-orange-600">Uploading image...</p>
    </ng-template>

    <!-- Success Template -->
    <ng-template #successTemplate>
      <img 
        [src]="uploadedImageUrl" 
        alt="Uploaded" 
        class="mx-auto h-32 w-32 object-cover rounded-lg"
      >
      <p class="text-sm text-green-600 font-medium">✓ Image uploaded successfully</p>
      <button
        type="button"
        (click)="uploadedImageRemoved.emit()"
        class="bg-red-600 hover:bg-red-700 text-white px-3 py-1 text-sm rounded transition-colors"
      >
        Remove Image
      </button>
    </ng-template>
  `
})
export class ImageUploadComponent {
  @Input() selectedImage: ImageFile | null = null;
  @Input() uploadedImageUrl = '';
  @Input() isUploading = false;

  @Output() imageSelected = new EventEmitter<ImageFile>();
  @Output() imageRemoved = new EventEmitter<void>();
  @Output() uploadedImageRemoved = new EventEmitter<void>();

  private cloudinaryService = inject(CloudinaryService);
  private toastr = inject(ToastrService);

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];

    if (!file) return;

    // Validate file
    if (!this.cloudinaryService.isValidImageFile(file)) {
      this.toastr.error('Please select a valid image file (JPEG, PNG, GIF, WebP) under 5MB', 'Invalid File');
      return;
    }

    // Create preview
    const reader = new FileReader();
    reader.onload = (e) => {
      const imageFile: ImageFile = {
        file,
        preview: e.target?.result as string
      };
      this.imageSelected.emit(imageFile);
    };
    reader.readAsDataURL(file);

    // Reset input
    input.value = '';
  }

  getFileSize(bytes: number): string {
    return this.cloudinaryService.getReadableFileSize(bytes);
  }
}

// frontend/src/components/report/ImageUpload.tsx
'use client';
import { useRef } from 'react';
import { useUpload } from '@/hooks/useUpload';

interface ImageUploadProps {
  selectedImage: File | null;
  uploadedImageUrl: string | null;
  isUploading: boolean;
  onImageSelected: (file: File) => void;
  onImageRemoved: () => void;
  onUploadedImageRemoved: () => void;
}

export default function ImageUpload({
  selectedImage,
  uploadedImageUrl,
  isUploading,
  onImageSelected,
  onImageRemoved,
  onUploadedImageRemoved,
}: ImageUploadProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { isValidImageFile, getReadableFileSize } = useUpload();

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      if (!isValidImageFile(file)) {
        alert('Please select a valid image file (JPEG, PNG, or WebP) under 5MB.');
        return;
      }
      onImageSelected(file);
    }
  };

  const triggerFileInput = () => {
    fileInputRef.current?.click();
  };

  if (isUploading) {
    return (
      <div className="border-2 border-dashed border-orange-300 rounded-xl p-8 text-center bg-orange-50">
        <div className="flex flex-col items-center gap-3">
          <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-orange-500"></div>
          <p className="text-sm text-gray-600">Uploading image...</p>
        </div>
      </div>
    );
  }

  if (uploadedImageUrl) {
    return (
      <div className="border-2 border-green-300 rounded-xl p-4 bg-green-50">
        <div className="flex flex-col items-center gap-3">
          <img
            src={uploadedImageUrl}
            alt="Uploaded"
            className="w-full max-h-48 object-cover rounded-lg"
          />
          <div className="flex items-center gap-2 text-green-600">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            <span className="text-sm font-medium">Image uploaded successfully</span>
          </div>
          <button
            type="button"
            onClick={onUploadedImageRemoved}
            className="text-sm text-red-500 hover:text-red-700 font-medium"
          >
            Remove Image
          </button>
        </div>
      </div>
    );
  }

  if (selectedImage) {
    return (
      <div className="border-2 border-orange-300 rounded-xl p-4 bg-orange-50">
        <div className="flex flex-col items-center gap-3">
          <img
            src={URL.createObjectURL(selectedImage)}
            alt="Preview"
            className="w-full max-h-48 object-cover rounded-lg"
          />
          <div className="text-sm text-gray-600">
            <p className="font-medium">{selectedImage.name}</p>
            <p>{getReadableFileSize(selectedImage.size)}</p>
          </div>
          <div className="flex gap-3">
            <button
              type="button"
              onClick={onImageRemoved}
              className="text-sm text-red-500 hover:text-red-700 font-medium"
            >
              Remove
            </button>
            <button
              type="button"
              onClick={triggerFileInput}
              className="text-sm text-orange-500 hover:text-orange-700 font-medium"
            >
              Change
            </button>
          </div>
        </div>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/jpeg,image/jpg,image/png,image/webp"
          onChange={handleFileChange}
          className="hidden"
        />
      </div>
    );
  }

  return (
    <div className="border-2 border-dashed border-gray-300 rounded-xl p-8 text-center hover:border-orange-400 transition-colors">
      <div className="flex flex-col items-center gap-3">
        <svg className="w-12 h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
        <button
          type="button"
          onClick={triggerFileInput}
          className="px-4 py-2 bg-orange-500 text-white rounded-lg hover:bg-orange-600 transition-colors text-sm font-medium"
        >
          Choose Image
        </button>
        <p className="text-xs text-gray-500">JPEG, PNG, or WebP (max 5MB)</p>
      </div>
      <input
        ref={fileInputRef}
        type="file"
        accept="image/jpeg,image/jpg,image/png,image/webp"
        onChange={handleFileChange}
        className="hidden"
      />
    </div>
  );
}
